# odev çözümleri
## labirent
[Labirent-1](https://blockly.games/maze?lang=tr&level=1#799rk7)  
[Labirent-2](https://blockly.games/maze?lang=tr&level=2&&skin=0#sy2wgz)  
[Labirent-3](https://blockly.games/maze?lang=tr&level=3&&skin=0#hreuuk)  
[Labirent-4](https://blockly.games/maze?lang=tr&level=4&&skin=0#7papve)  
[Labirent-5](https://blockly.games/maze?lang=tr&level=5&&skin=0#eurztc)  
[Labirent-6](https://blockly.games/maze?lang=tr&level=6&&skin=0#uqrpsv)  
[Labirent-7](https://blockly.games/maze?lang=tr&level=7&&skin=0#hbbx6m)  
[Labirent-8](https://blockly.games/maze?lang=tr&level=8&&skin=0#9ch4vx)  
[Labirent-9](https://blockly.games/maze?lang=tr&level=9&&skin=0#o3mnu7)  
[Kaplunbağa-1](https://blockly.games/turtle?lang=tr&level=1#zh94rt)
[Kaplunbağa-2](https://blockly.games/turtle?lang=tr&level=2#7gwpzt)  
[Kaplunbağa-3](https://blockly.games/turtle?lang=tr&level=3#ggebae)  
[Kaplunbağa-4](https://blockly.games/turtle?lang=tr&level=4#cfbuo3)  
[Kaplunbağa-5](https://blockly.games/turtle?lang=tr&level=5#xqo25v)  
[Kaplunbağa-6](https://blockly.games/turtle?lang=tr&level=6#p262pj)  
[Kaplunbağa-7](https://blockly.games/turtle?lang=tr&level=7#uimq34)  
[Kaplunbağa-8](https://blockly.games/turtle?lang=tr&level=8#q2dphe)  
[Kaplunbağa-9](https://blockly.games/turtle?lang=tr&level=9#oiu2dy)  
[Flim1](https://blockly.games/movie?lang=tr&level=1#rhmhiw)  
[Flim2](https://blockly.games/movie?lang=tr&level=2#i8k9ct)  
[Flim3](https://blockly.games/movie?lang=tr&level=3#xk9w25)  
[Flim4](https://blockly.games/movie?lang=tr&level=4#8kxv8p)  
[Flim5](TEZGAHUSTKAPANA2.5MM)
[Flim6](https://blockly.games/movie?lang=tr&level=6#mi3x23)
[Flim7](https://blockly.games/movie?lang=tr&level=7#uwqrmn)
[Flim8]
